language: python
cache: pip
dist: bionic
matrix:
  include:
    - os: linux
      python: "3.7"
    - os: osx
      language: generic
addons:
  apt:
    packages:
      - mecab
      - libmecab-dev
      - unidic-mecab
      - swig
  homebrew:
    packages:
      - python3
      - mecab
      - mecab-unidic
      - swig
    #update: true
install:
  - make setup
script:
  - make lint
  - make test
notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      - https://outlook.office.com/webhook/216e4f60-123d-4483-bb9a-0b31d0810cb2@c1a3ad8b-49cc-4a52-9ec7-533f7ff2b9a5/TravisCI/9cab754aa833470290957edb301af718/5195db10-93c4-4b8b-bca3-2da3a7c776bd
    on_success: change
    on_failure: always
